                extrn GetFileSize:Proc
                extrn GlobalAlloc:Proc
                extrn GlobalFree:Proc
                extrn ExitProcess:Proc
                extrn CloseHandle:Proc
                extrn WriteFile:Proc
                extrn GetModuleHandleA:Proc
                extrn CreateFileA:Proc
                extrn ReadFile:Proc

                extrn GetOpenFileNameA:Proc
                extrn GetSaveFileNameA:Proc
